### ISSUE TITLE
看板定制，多图表出现问题

### ISSUE THREAD

**Issue by tzw28** [eeyshen/AutoVis-issues#19]
Windows Chrome
![image](https://user-images.githubusercontent.com/37988911/69129379-2c976b00-0ae9-11ea-9733-5e2cd1863a7c.png)
看板定制时，拖入第二个图表时，看板y轴长度变长，新的图表出现在下方，且拖拽不到上方。其后的图表都出现这个现象，每一个都拖不到与其他图表平行的位置。

**Comment by shenenya** [comment]
fixed.
