### ISSUE TITLE
图表创建方式优化

### ISSUE THREAD

**Issue by tzw28** [eeyshen/AutoVis-issues#2]
对于 “时间-属性1-……-属性n-总量-分量1-分量2-……” 这样形式的数据，建立图表的方式不够直接，目前需要：

- 转为两个表，一个 “时间-总量”，一个  “时间-分量类型-分量值”

- 编写transfrom字段，将数据转为需要的形式

可能的解决方法：

待讨论

**Comment by shenenya** [comment]
使用fold变换
