### ISSUE TITLE
图表刷新频率的影响

### ISSUE THREAD

**Issue by tzw28** [eeyshen/AutoVis-issues#3]
图表的刷新频率较高，目前每次参数发生变化都会刷新图表，可能会造成如下问题：

- 参数输入困难。输入参数时，图表会被刷新。打字稍快时光标焦点会被重置，影响输入。

![GIF](https://user-images.githubusercontent.com/37988911/66455893-a118cc00-ea9e-11e9-9018-a74c57dcfa10.gif)

- 数据量大时，重绘图表频率太高，计算压力很大，界面卡顿

**Comment by shenenya** [comment]
fixed.
