### ISSUE TITLE
数据上传，数据库连接问题

### ISSUE THREAD

**Issue by jiaojiangfeng** [eeyshen/AutoVis-issues#30]
- 无法上传本地的excel，csv文件
![image](https://user-images.githubusercontent.com/47909468/71609266-14276f80-2bc2-11ea-8aa5-20ee40ee035a.png)
进度条卡死，确定按钮为不可点击状态。
- 无法连接数据库
服务器与数据库之间端口连接是没问题的。
![image](https://user-images.githubusercontent.com/47909468/71609370-b6dfee00-2bc2-11ea-9fda-b1a90712c398.png)
服务器与数据库之间端口连接是没问题的。

**Comment by tzw28** [comment]
csv文件的问题，可能是由于文件编码导致的。
如果文件是GB2312格式，可以先在本地转成utf-8格式再尝试上传。
Windows转格式，可以使用记事本打开，另存为，选择编码。
![image](https://user-images.githubusercontent.com/37988911/71610957-5bb4f800-2bd0-11ea-9f2f-7e8e458a5c9c.png)
其他问题正在解决。

**Comment by tzw28** [comment]
> * 无法上传本地的excel，csv文件
>   ![image](https://user-images.githubusercontent.com/47909468/71609266-14276f80-2bc2-11ea-8aa5-20ee40ee035a.png)
>   进度条卡死，确定按钮为不可点击状态。
> * 无法连接数据库
>   服务器与数据库之间端口连接是没问题的。
>   ![image](https://user-images.githubusercontent.com/47909468/71609370-b6dfee00-2bc2-11ea-9fda-b1a90712c398.png)
>   服务器与数据库之间端口连接是没问题的。

如上。

**Comment by shenenya** [comment]
fixed.
