### ISSUE TITLE
单看板多图表数据过滤问题

### ISSUE THREAD

**Issue by Wangyb233** [eeyshen/AutoVis-issues#31]
单看板中有三个图表，通过url传过滤条件后只有一个图表发生变化，其他两个没有变化，三个图表使用的是同一数据。
![捕获2](https://user-images.githubusercontent.com/59222343/71791996-01a1b000-3072-11ea-875c-375386c776ed.PNG)
![捕获1](https://user-images.githubusercontent.com/59222343/71792000-04040a00-3072-11ea-9462-0489e206dc6d.PNG)
![捕获3](https://user-images.githubusercontent.com/59222343/71792004-06666400-3072-11ea-829f-0bd76da074b2.PNG)

**Comment by tzw28** [comment]
已处理，下次更新将修复。
如果需要临时修复，可以创建三个新的一样的图表，用三个新图表来构建看板，新的看板应该是可以正确传参的。

**Comment by Wangyb233** [comment]
更新后有bug
![批注 2020-01-10 092836](https://user-images.githubusercontent.com/59222343/72118526-556f0a80-338c-11ea-9700-741e0d24b794.png)

**Comment by shenenya** [comment]
fixed.
