### ISSUE TITLE
2 bugs 2020/05/11

### ISSUE THREAD

**Issue by sunnycsm** [eeyshen/AutoVis-issues#32]
Bug1 保存图表。重名之后这个图标就无法保存。
 
![image](https://user-images.githubusercontent.com/37916147/81546809-7c2a6580-93ad-11ea-93f8-cd133f2ae135.png)

Bug2 删除图表在当前页面不显示，页面刷新以后再显示。

**Comment by shenenya** [comment]
Bug1: 需要重命名再保存。
Bug2: 具体过程是？
BTW：建议一个issue包括一个问题。
