### ISSUE TITLE
Bug2 图表无法显示

### ISSUE THREAD

**Issue by sunnycsm** [eeyshen/AutoVis-issues#35]
Bug2 图表无法显示
选择显示图表
 
![image](https://user-images.githubusercontent.com/37916147/81667467-e1e22480-9475-11ea-9875-7433b00df557.png)

图表无法显示
![image](https://user-images.githubusercontent.com/37916147/81667482-e4dd1500-9475-11ea-8877-3d49107176f2.png)

**Comment by shenenya** [comment]
这里是指虚拟数据源的图表？

**Comment by sunnycsm** [comment]
![image](https://user-images.githubusercontent.com/37916147/81673342-16f27500-947e-11ea-8843-9af62ddc3d45.png)
任何一个名称带‘-’的图表都无法显示。数据源是layer1, layer2a等

**Comment by sunnycsm** [comment]
> 这里是指虚拟数据源的图表？

不是，这个图是今天上午你做的图。数据源是layer2a. 
![image](https://user-images.githubusercontent.com/37916147/81675315-350da480-9481-11ea-9891-0c7fffd01446.png)

**Comment by shenenya** [comment]
fixed.
