### ISSUE TITLE
051203 数据必须点运行才能显示，否则无法显示

### ISSUE THREAD

**Issue by sunnycsm** [eeyshen/AutoVis-issues#36]
Bug3 数据必须点运行才能显示，否则无法显示
![image](https://user-images.githubusercontent.com/37916147/81667579-0807c480-9476-11ea-8e3c-6c832905cf9b.png)
![image](https://user-images.githubusercontent.com/37916147/81667653-1ce45800-9476-11ea-9c4b-a01607dabcc6.png)

**Comment by shenenya** [comment]
在这里测试是可以的，这个问题的操作步骤是？尝试其他数据源是否也有这个问题？

**Comment by shenenya** [comment]
fixed.
