### ISSUE TITLE
访问PG数据源失败

### ISSUE THREAD

**Issue by sunnycsm** [eeyshen/AutoVis-issues#38]
![image](https://user-images.githubusercontent.com/37916147/82182312-a54f7680-9916-11ea-86df-808f84becc1d.png)

**Comment by shenenya** [comment]
具体的PG数据源是？

**Comment by sunnycsm** [comment]
> 具体的PG数据源是？

101.6.15.211--sifangsuo--layer1_813_to_816

**Comment by shenenya** [comment]
刚刚试了试，用http://101.6.240.89:18080/可以正常打开这个表。
<img width="595" alt="截屏2020-05-19 下午3 25 35" src="https://user-images.githubusercontent.com/31716017/82297374-270dd580-99e5-11ea-87f7-b06c70de5191.png">
<img width="3008" alt="截屏2020-05-19 下午3 26 05" src="https://user-images.githubusercontent.com/31716017/82297394-2d9c4d00-99e5-11ea-9982-755a2cd2453a.png">

**Comment by sunnycsm** [comment]
> 刚刚试了试，用[http://101.6.240.89:18080/可以正常打开这个表。](http://101.6.240.89:18080/%E5%8F%AF%E4%BB%A5%E6%AD%A3%E5%B8%B8%E6%89%93%E5%BC%80%E8%BF%99%E4%B8%AA%E8%A1%A8%E3%80%82)
> <img alt="截屏2020-05-19 下午3 25 35" width="595" src="https://user-images.githubusercontent.com/31716017/82297374-270dd580-99e5-11ea-87f7-b06c70de5191.png">
> <img alt="截屏2020-05-19 下午3 26 05" width="2000" src="https://user-images.githubusercontent.com/31716017/82297394-2d9c4d00-99e5-11ea-9982-755a2cd2453a.png">

ok
