### ISSUE TITLE
Bug0520-01: 图表无法保存，报错信息"重名"。但图表不重名。

### ISSUE THREAD

**Issue by sunnycsm** [eeyshen/AutoVis-issues#40]
![image](https://user-images.githubusercontent.com/37916147/82397260-a30a2b00-9a82-11ea-8c6f-ef5f5458730f.png)

**Comment by shenenya** [comment]
这里尝试没有发现这个问题，操作步骤是？

**Comment by shenenya** [comment]
fixed.
