### ISSUE TITLE
Bug-0520-02每次更改看板都需要改每张图表名字再保存

### ISSUE THREAD

**Issue by sunnycsm** [eeyshen/AutoVis-issues#41]
看板更改以后必须xian先更改3张图表的名字，再选看板-覆盖
![image](https://user-images.githubusercontent.com/37916147/82417992-f8f4c800-9aae-11ea-83fc-d6de89b8b972.png)

**Comment by shenenya** [comment]
这是一个强制的约束，避免使用历史版本图表的看板出现问题。如果编辑看板时，某个图表没有任何修改，可以不用重命名，新保存的看板将保留原图表。
