### ISSUE TITLE
Bug 0522-1 Autovis看板无法显示     

### ISSUE THREAD

**Issue by sunnycsm** [eeyshen/AutoVis-issues#42]
![image](https://user-images.githubusercontent.com/37916147/82648765-ba941000-9c4a-11ea-979b-0c91c7124387.png)

 
![image](https://user-images.githubusercontent.com/37916147/82648772-bf58c400-9c4a-11ea-99af-ca666f638833.png)

**Comment by shenenya** [comment]
数据源访问不了了
