### ISSUE TITLE
issues with docs

### ISSUE THREAD

**Issue by 815382636** [eeyshen/AutoVis-issues#43]
1.通过数据创建的图表查看按钮无法使用。
2.看板中心当关闭图表页面时无法再新建，只有刷新才能初始化。
3.因为图表的问题，看板新建时显示的图表是空数据。
4.新建的看板无法保存，使用任何名字都显示重名。
5.创建的图表和看板加提示。

**Comment by shenenya** [comment]
4和5是指？
fixed: 1, 2
todo: 3

**Comment by 815382636** [comment]
第四个问题就是当新建一个新的看板时，有时候并没有重名但会一直显示重名，无论怎么改都显示重名，但刷新几遍重新新建这个问题就没了，出现过3次
第五个问题是当新建完一个图表或看板时，是否需要加一个提示表示创建成功？第五个不是bug，只是一点建议




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "E.Y. Shen"<notifications@github.com&gt;; 
发送时间: 2020年5月25日(星期一) 中午11:52
收件人: "eeyshen/AutoVis-issues"<AutoVis-issues@noreply.github.com&gt;; 
抄送: "岳魏琦"<815382636@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [eeyshen/AutoVis-issues] issues with docs (#43)





 
4和5是指？
 fixed: 1, 2
 todo: 3

**Comment by shenenya** [comment]
4: 留意一下复现这个问题的步骤，方便后续解决；
5: fixed.

**Comment by shenenya** [comment]
fixed.
