### ISSUE TITLE
查看数据

### ISSUE THREAD

**Issue by 815382636** [eeyshen/AutoVis-issues#46]
数据的查看按钮没有问题，但点数据那一行，查看的确实列表

**Comment by shenenya** [comment]
描述不清楚，缺失？

**Comment by 815382636** [comment]
数据列表中点击某一行的意思应该是查看这一行的数据，跟查看按钮一个功能，但点击这一行，却成了他生成的图表
比如说我新建了一个数据，我没用他生成图表，我点击那一行，却出现了图表。。这是问题吗，还是我理解不对




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "E.Y. Shen"<notifications@github.com&gt;; 
发送时间: 2020年5月25日(星期一) 晚上8:10
收件人: "eeyshen/AutoVis-issues"<AutoVis-issues@noreply.github.com&gt;; 
抄送: "岳魏琦"<815382636@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [eeyshen/AutoVis-issues] 查看数据 (#46)





 
描述不清楚，缺失？

**Comment by shenenya** [comment]
fixed.
