### ISSUE TITLE
数据查找

### ISSUE THREAD

**Issue by 815382636** [eeyshen/AutoVis-issues#49]
手册中数据查找中写道：系统将根据用户输入关键字，在名称、分类、作者和来源中查找包含关键字的条目。1.若分类为未分类，查找未分类不显示数据。2.无法根据来源中的关键字检索。

**Comment by 815382636** [comment]
图表也存在此问题

**Comment by 815382636** [comment]
看板也存在此问题

**Comment by shenenya** [comment]
1. fixed.
2. 不支持根据来源过滤。
