### ISSUE TITLE
本地上传.xlsx文件提示“上传失败”

### ISSUE THREAD

**Issue by MichaelLee826** [eeyshen/AutoVis-issues#54]
数据—新建—本地数据，选择本地的.xlsx文件时，提示“错误，上传失败”；选择本地.xls文件时，没有成功，但无任何提示
另外，建议在文档中补充支持本地上传的文件类型

**Comment by tzw28** [comment]
> 数据—新建—本地数据，选择本地的.xlsx文件时，提示“错误，上传失败”；选择本地.xls文件时，没有成功，但无任何提示
> 另外，建议在文档中补充支持本地上传的文件类型

请问.xlsx文件大概是什么结构？其中有图表吗？
