### ISSUE TITLE
个别图表无法通过鼠标改变大小

### ISSUE THREAD

**Issue by MichaelLee826** [eeyshen/AutoVis-issues#56]
个别图表选中后没有显示边框，也无法通过鼠标拖拽改变图表的大小，例如：条形图中的“条形图+分组”、交互式多图表中的“交互式散点矩阵”等

**Comment by shenenya** [comment]
1. 在分组类型的单图表中通过增加
```
“宽”: {"步长": 10}
```
选项，修改其中的步长大小控制图表宽度。这种情况下，无法通过鼠标拖拽修改宽度，可以修改高度。

2. 对于多图表类型的图表模板，可以通过修改“通用选项”中的“外边界”控制多图表的内边界大小，当增加边界时，将可以看到拖拽边，用鼠标调整大小。
