### ISSUE TITLE
The visual panel looks very slow

### ISSUE THREAD

**Issue by DahaiCAO** [eeyshen/AutoVis-issues#57]
The visual panel looks very slow.

![image](https://user-images.githubusercontent.com/10430776/91270008-934d6180-e7aa-11ea-878d-d5bb76ecd11e.png)

**Comment by shenenya** [comment]
可能原因：1. AutoVis系统性能低；2. 网络速度影响；3. DWF加载速度影响。
能否记录一下单独打开该看板、用DWF加载，以及这两种情况在校内操作的耗时。
