### ISSUE TITLE
Visual panel can not self-adopt form

### ISSUE THREAD

**Issue by DahaiCAO** [eeyshen/AutoVis-issues#58]
Visual panel can not self-adopt form

![image](https://user-images.githubusercontent.com/10430776/91271655-1bcd0180-e7ad-11ea-8273-cd94aecf82f4.png)

![image](https://user-images.githubusercontent.com/10430776/91271729-356e4900-e7ad-11ea-92ae-584971361500.png)

**Comment by shenenya** [comment]
这里需要确认定义该图表时有没有锁定图表宽高，或定义看板时仅让该图表占用页面一部分。建议直接打开对应看板，看其是否可以填满浏览器。
