### ISSUE TITLE
The 29th visual panel can not accept the parameter of "tableName"

### ISSUE THREAD

**Issue by DahaiCAO** [eeyshen/AutoVis-issues#59]
http://101.6.15.211:8000/dashboards/layer1-stationConsu?datasourceID=29&tableName=shanghai_17hongqiao_17A01_layer2b&时间=['2019-8-12', '2019-8-19']&站台={'东方绿洲站下行站台','诸光路站下行站台','蟠龙路站下行站台'}

![image](https://user-images.githubusercontent.com/10430776/91279640-50928600-e7b8-11ea-8a7b-42ad41cdfa64.png)

**Comment by eeyshen** [comment]
这个数据集可能有问题，根据太志伟反馈，29号数据集所依赖的数据源可能已经被删除，导致该功能无法使用。

**Comment by shenenya** [comment]
fixed.
