### ISSUE TITLE
If I updated DB table columns, the 26th dataset in AutoVis does not work. It can not be modified as well. 

### ISSUE THREAD

**Issue by DahaiCAO** [eeyshen/AutoVis-issues#62]
It is a problem.

![image](https://user-images.githubusercontent.com/10430776/92567606-83f10c80-f2b0-11ea-988e-f4dae0cac909.png)

![image](https://user-images.githubusercontent.com/10430776/92567680-9d925400-f2b0-11ea-81ee-178d1fff7cc8.png)

![image](https://user-images.githubusercontent.com/10430776/92567692-a3883500-f2b0-11ea-8592-c88bead4ec9c.png)

**Comment by shenenya** [comment]
fixed.
